### ISSUE TITLE
glacier2router: warning: connection exception:

### ISSUE THREAD

**Issue by dengly** [dengly/Ice-demo#15]
在使用glacier2+grid，当客户端连接glacier2时报以下异常。通过度娘搜索，都是千篇一律的结果，如http://www.php230.com/ice-common-compile-and-run-error.html。但是这里提供的解决方法有待考究，因为也没有详细说明如何解决。
```
-! 04/25/17 09:11:07.120 glacier2router: warning: connection exception:
   StreamSocket.cpp:202: Ice::ConnectionLostException:
   connection lost: recv() returned zero
   local address = ::ffff:120.26.78.171:6063
   remote address = ::ffff:120.1.245.22:22480

-! 04/25/17 09:21:21.270 glacier2router: warning: connection exception:
   StreamSocket.cpp:218: Ice::ConnectionLostException:
   connection lost: recv() returned zero
   local address = ::ffff:118.178.229.243:6063
   remote address = ::ffff:120.1.245.22:22778

-! 04/25/17 09:21:27.468 glacier2router: warning: connection exception:
   OpenSSLTransceiverI.cpp:525: Ice::ConnectionLostException:
   connection lost: recv() returned zero
   local address = ::ffff:120.26.78.171:6064
   remote address = ::ffff:117.136.103.82:13771
```

**Comment by viviwei-py** [comment]
![image](https://cloud.githubusercontent.com/assets/10277030/26163266/bdd036de-3b5b-11e7-923c-f5ed076a293e.png)
-! 05/17/17 23:48:45.048 icegridnode: warning: Proxy contains unknown endpoints: `ssl -h 127.0.0.1 -p 4063'
java.lang.UnsupportedClassVersionError: com/zzwtec/iceTicketProject/ice/Sl4jIceBoxServer : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(Unknown Source)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$000(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
Could not find the main class: com.zzwtec.iceTicketProject.ice.Sl4jIceBoxServer.  Program will exit.
Exception in thread "main" 

能帮忙看什么问题？
我指定的	<env>CLASSPATH=D:\Program Files (x86)\ZeroC\Ice-3.6.1\lib\*;E:\workspace\iceTicketProject\target\lib\*;E:\workspace\iceTicketProject\target\classes</env>
