### ISSUE TITLE
这个是什么问题

### ISSUE THREAD

**Issue by net-wade** [dengly/Ice-demo#16]
image
-! 05/17/17 23:48:45.048 icegridnode: warning: Proxy contains unknown endpoints: `ssl -h 127.0.0.1 -p 4063'
java.lang.UnsupportedClassVersionError: com/zzwtec/iceTicketProject/ice/Sl4jIceBoxServer : Unsupported major.minor version 51.0
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClassCond(Unknown Source)
at java.lang.ClassLoader.defineClass(Unknown Source)
at java.security.SecureClassLoader.defineClass(Unknown Source)
at java.net.URLClassLoader.defineClass(Unknown Source)
at java.net.URLClassLoader.access$000(Unknown Source)
at java.net.URLClassLoader$1.run(Unknown Source)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
Could not find the main class: com.zzwtec.iceTicketProject.ice.Sl4jIceBoxServer. Program will exit.
Exception in thread "main"

能帮忙看什么问题？
我指定的	CLASSPATH=D:\Program Files (x86)\ZeroC\Ice-3.6.1\lib*;E:\workspace\iceTicketProject\target\lib*;E:\workspace\iceTicketProject\target\classes

**Comment by dengly** [comment]
检测一下你的java开发环境是否设置好

**Comment by dengly** [comment]
你依赖的Jar需要的jdk比你设置的jdk版本高
