### ISSUE TITLE
Ice 3.6.1的自定义异常处理，报Ice.UnknownUserException

### ISSUE THREAD

**Issue by dengly** [dengly/Ice-demo#6]
slice定义如下：

```
[["java:package:com.my"]]
module demo{
        exception GenericError {
            string reason;
        };
        interface MyService{
            idempotent string hellow() throws GenericError; 
        };
};
```

在运行时报了以下错误：

```
Ice.UnknownUserException
    unknown = "demo::GenericError"
        at IceInternal.BasicStream$EncapsDecoder11.skipSlice(BasicStream.java:3798)
        at IceInternal.BasicStream$EncapsDecoder11.throwException(BasicStream.java:3599)
        at IceInternal.BasicStream.throwException(BasicStream.java:2285)
        at IceInternal.OutgoingAsync.throwUserException(OutgoingAsync.java:399)
        at com.my.demo.MyServicePrxHelper.end_hellow(MyServicePrxHelper.java:156)
        at com.my.demo.MyServicePrxHelper.hellow(MyServicePrxHelper.java:43)
        at com.my.demo.MyServicePrxHelper.hellow(MyServicePrxHelper.java:30)
        at com.my.demoImpl.MyClient.main(MyClient.java:18)
```

这个Ice的Bug，解决办法是修改slice生成的GenericError.java类，修改ice_name和__writeImpl方法，修改如下：

```
    public String ice_name() {
            return "com::my::demo::GenericError";
    }
    protected void  __writeImpl(IceInternal.BasicStream __os) {
            __os.startWriteSlice("::com::my::demo::GenericError", -1, true);
            __os.writeString(reason);
            __os.endWriteSlice();
    }
```

你会发现Ice在生成自定义异常文件时这个异常的ice_name和id缺少了包名，如果没有定义java的package是没有错误的，能够正常抛出你所期待的异常信息。

**Comment by dengly** [comment]
还有网友提供了另一种解决办法，就是修改slice的定义文件，修改如下：

```
module com{
module my{
module demo{
        exception GenericError {
            string reason;
        };
        interface MyService{
            idempotent string hellow() throws GenericError; 
        };
};
};
};
```
